development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: needp_development

test:
  adapter: async

production:
  adapter: redis
  url: "REDIS_URL"
  channel_prefix: needp_production
