# This file contains configurations for both PostgreSQL and MySQL, uncomment
# the one you wish to use and keep the other commented out.

# -------------------------------- PostgreSQL ----------------------------------
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # The following username and password are used for both development and test
  # environments.
  username: postgres
  password: Monkey!

development:
  <<: *default
  database: needp_development

test:
  <<: *default
  database: needp_test

  # HEROKU
  # Heroku uses the DATABASE_URL environment variable to configure the DB
  # connection. You should *NOT* set adapter, database, username, password, host
  # or port in this file.

  # AMAZON ELASTIC BEANSTALK + AMAZON RDS
  # These environment variables are available in any Beanstalk environment
  # that is linked to an RDS instance.
  # database: <%= ENV['RDS_DB_NAME'] %>
  # username: <%= ENV['RDS_USERNAME'] %>
  # password: <%= ENV['RDS_PASSWORD'] %>
  # host: <%= ENV['RDS_HOSTNAME'] %>
  # port: <%= ENV['RDS_PORT'] %>

# ---------------------------------  MySQL -------------------------------------
#default: &default
#  adapter: mysql2
#  encoding: utf8
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  # The following username and password are used for both development and test
#  # environments.
#  username: root
#  password: localdbpass
#  socket: /var/run/mysqld/mysqld.sock
#
#development:
#  <<: *default
#  database: needp_development
#
#test:
#  <<: *default
#  database: needp_test
#
production:
  <<: *default
  encoding: utf8
  database: dd5mdefm1m0pgi
  username: miavioghvxfnok
  password: 571fabb6ee3dfa6bf7fed86de00b1c837870ba5959b05bf57a9a683cfe9f918b
  host: ec2-107-22-160-102.compute-1.amazonaws.com
  port: 5432
