# This file contains configurations for both PostgreSQL and MySQL, uncomment
# the one you wish to use and keep the other commented out.

# -------------------------------- PostgreSQL ----------------------------------
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # The following username and password are used for both development and test
  # environments.
  username: postgres
  password: Monkey!

development:
  <<: *default
  database: needp_development

test:
  <<: *default
  database: needp_test

  # HEROKU
  # Heroku uses the DATABASE_URL environment variable to configure the DB
  # connection. You should *NOT* set adapter, database, username, password, host
  # or port in this file.

  # AMAZON ELASTIC BEANSTALK + AMAZON RDS
  # These environment variables are available in any Beanstalk environment
  # that is linked to an RDS instance.
  # database: <%= ENV['RDS_DB_NAME'] %>
  # username: <%= ENV['RDS_USERNAME'] %>
  # password: <%= ENV['RDS_PASSWORD'] %>
  # host: <%= ENV['RDS_HOSTNAME'] %>
  # port: <%= ENV['RDS_PORT'] %>

# ---------------------------------  MySQL -------------------------------------
#default: &default
#  adapter: mysql2
#  encoding: utf8
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  # The following username and password are used for both development and test
#  # environments.
#  username: root
#  password: localdbpass
#  socket: /var/run/mysqld/mysqld.sock
#
#development:
#  <<: *default
#  database: needp_development
#
#test:
#  <<: *default
#  database: needp_test
#
production:
  <<: *default
  encoding: utf8
  database: d4b1rq7okppq32
  username: wszjrbgqjkoojj
  password: de80df30d8bf3cc5003cba6f484c5e161b72822f2da73c2c332df91ebfb6a585
  host: ec2-23-21-87-183.compute-1.amazonaws.com
  port: 5432
